# Form implementation generated from reading ui file 'show-pixels-in-image-widget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_point_in_image_form(object):
    def setupUi(self, point_in_image_form):
        point_in_image_form.setObjectName("point_in_image_form")
        point_in_image_form.resize(940, 687)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(point_in_image_form.sizePolicy().hasHeightForWidth())
        point_in_image_form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(point_in_image_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(point_in_image_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.image_information = PointsInImageImageInformationWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_information.sizePolicy().hasHeightForWidth())
        self.image_information.setSizePolicy(sizePolicy)
        self.image_information.setObjectName("image_information")
        self.image_information.setColumnCount(0)
        self.image_information.setRowCount(0)
        self.image_information.horizontalHeader().setVisible(False)
        self.image_information.verticalHeader().setVisible(False)
        self.table = PointsInImageImageWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.table.horizontalHeader().setVisible(False)
        self.table.horizontalHeader().setHighlightSections(False)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(point_in_image_form)
        QtCore.QMetaObject.connectSlotsByName(point_in_image_form)

    def retranslateUi(self, point_in_image_form):
        _translate = QtCore.QCoreApplication.translate
        point_in_image_form.setWindowTitle(_translate("point_in_image_form", "Form"))
from ba_trees.gui.image_pixel_widget.PointsInImageWidget import PointsInImageImageInformationWidget, PointsInImageImageWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    point_in_image_form = QtWidgets.QWidget()
    ui = Ui_point_in_image_form()
    ui.setupUi(point_in_image_form)
    point_in_image_form.show()
    sys.exit(app.exec())
