# Form implementation generated from reading ui file 'show-pixel-in-image-widget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_point_in_image_form(object):
    def setupUi(self, point_in_image_form):
        point_in_image_form.setObjectName("point_in_image_form")
        point_in_image_form.resize(940, 708)
        self.verticalLayout = QtWidgets.QVBoxLayout(point_in_image_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = PointInImageTableWidget(point_in_image_form)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)

        self.retranslateUi(point_in_image_form)
        QtCore.QMetaObject.connectSlotsByName(point_in_image_form)

    def retranslateUi(self, point_in_image_form):
        _translate = QtCore.QCoreApplication.translate
        point_in_image_form.setWindowTitle(_translate("point_in_image_form", "Form"))
from ba_trees.gui.image_pixel_widget.PointInImageWidget import PointInImageTableWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    point_in_image_form = QtWidgets.QWidget()
    ui = Ui_point_in_image_form()
    ui.setupUi(point_in_image_form)
    point_in_image_form.show()
    sys.exit(app.exec())
